(() => {
  'use strict';
  const cfg=window.VITALCARE_CONFIG;const form=document.getElementById('loginForm');const errorBox=document.getElementById('loginError');const button=document.getElementById('loginButton');const cpfInput=document.getElementById('cpf');const birthInput=document.getElementById('birthDate');const networkMessage=document.getElementById('networkMessage');
  const digits=v=>String(v||'').replace(/\D/g,'');
  function maskCPF(value){const v=digits(value).slice(0,11);return v.replace(/^(\d{3})(\d)/,'$1.$2').replace(/^(\d{3})\.(\d{3})(\d)/,'$1.$2.$3').replace(/\.(\d{3})(\d)/,'.$1-$2');}
  function showError(message){errorBox.textContent=message;errorBox.classList.add('show');}
  function clearError(){errorBox.classList.remove('show');errorBox.textContent='';}
  function setBusy(on){button.disabled=on;button.querySelector('span').textContent=on?'Validando acesso...':'Acessar Minha Fila';button.querySelector('b').textContent=on?'…':'→';}
  function updateNetwork(){const offline=!navigator.onLine;networkMessage.classList.toggle('show',offline);networkMessage.textContent=offline?'Você está sem internet. Conecte-se para acessar os dados do atendimento.':'';if(offline)button.disabled=true;else if(!button.dataset.busy)button.disabled=false;}
  function updateClock(){try{document.getElementById('loginClock').textContent=`Brasília · ${new Intl.DateTimeFormat('pt-BR',{timeZone:cfg?.timeZone||'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'}).format(new Date())}`;}catch(_){}}
  if(!cfg||!window.supabase?.createClient){showError('Não foi possível iniciar a conexão segura. Verifique sua internet e tente novamente.');button.disabled=true;return;}
  const client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storage:window.sessionStorage}});
  cpfInput.addEventListener('input',()=>{cpfInput.value=maskCPF(cpfInput.value);clearError();});birthInput.addEventListener('change',clearError);birthInput.max=new Date().toISOString().slice(0,10);
  async function reuseSessionIfValid(){try{const{data:{session}}=await client.auth.getSession();if(!session)return;const{data,error}=await client.from('atendimentos').select('id').order('inicio_em',{ascending:false}).limit(1);if(!error&&data?.length){sessionStorage.setItem('vc-atendimento-id',data[0].id);location.replace(cfg.homePage);}}catch(_){}}
  form.addEventListener('submit',async event=>{event.preventDefault();clearError();if(!navigator.onLine){showError('Você está sem internet. Conecte-se e tente novamente.');return;}const cpf=digits(cpfInput.value);const birthDate=birthInput.value;if(cpf.length!==11||!birthDate){showError('Confira o CPF e a data de nascimento.');return;}button.dataset.busy='1';setBusy(true);try{await client.auth.signOut({scope:'local'}).catch(()=>{});const{error:authError}=await client.auth.signInAnonymously();if(authError)throw authError;const{data,error}=await client.rpc('entrar_minha_fila',{p_cpf:cpf,p_data_nascimento:birthDate});if(error)throw error;if(!data?.ok||!data?.atendimento_id){await client.auth.signOut({scope:'local'}).catch(()=>{});throw new Error(data?.mensagem||'Não foi possível acessar com os dados informados.');}sessionStorage.setItem('vc-atendimento-id',data.atendimento_id);sessionStorage.setItem('vc-login-em',new Date().toISOString());location.replace(cfg.homePage);}catch(error){await client.auth.signOut({scope:'local'}).catch(()=>{});showError(error?.message||'Não foi possível acessar com os dados informados. Tente novamente mais tarde.');}finally{delete button.dataset.busy;setBusy(false);updateNetwork();}});
  window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);updateNetwork();updateClock();setInterval(updateClock,30000);reuseSessionIfValid();
})();
